//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtkdK22CNT3Lesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LtkdAccount
    {
        public int LtkdID { get; set; }
        public string LtkdUserName { get; set; }
        public string LtkdPassword { get; set; }
        public string LtkdFullName { get; set; }
        public string LtkdEmail { get; set; }
        public string LtkdPhone { get; set; }
        public Nullable<bool> LtkdActive { get; set; }
    }
}
